version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies
      - npm install
  build:
    commands:
      - echo Build completed
  post_build:
    commands:
      - echo Zipping app for CodeDeploy
      - zip -r myapp.zip . appspec.yaml scripts/

artifacts:
  files:
    - myapp.zip
