version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies
      - npm install
      - chmod +x scripts/*.sh
  build:
    commands:
      - echo Build completed
  post_build:
    commands:
      - echo Zipping app for CodeDeploy
      - zip -r myapp.zip . -x "*.git*"  # include everything except .git folder

artifacts:
  files:
    - myapp.zip
